### ISSUE TITLE
What if index.html doesn't exist?

### ISSUE THREAD

**Issue by davorg** [ranguard/plack-middleware-dirindex#3]
I was trying to use this last night when I realised a slight problem with it. I think the behaviour should be:

    if path ends with /
      if index.html exists
        append index.html to path
      else
        do nothing (so directory listing is displayed)
      end
    else
      do nothing (so file is displayed)
    end

But I can't see an obvious way to do that.

Currently, if you turn this on and there's no index.html, then you get a 404.

**Comment by nichtich** [comment]
Try [Plack::Middleware::Static](https://metacpan.org/pod/Plack::Middleware::Static) instead or Plack::Middleware::DirIndex should get a `pass_through` option as well.

**Comment by davorg** [comment]
Earlier this year, I released a version of Plack::Middleware::DirIndex which fixes this problem. Sorry, I should have closed this ticket at the time.

https://metacpan.org/release/DAVECROSS/Plack-Middleware-DirIndex-1.01
